name: Test Github Packages - Push

on:
  push:
    branches: [ main ]
    tags: [ v1* ]
    
env:
  ASDF: asdf_variable
    
jobs:
  branch:
    if: ${{ github.ref_type == 'branch' }}
    runs-on: ubuntu-latest
    environment:
      name: ${{ fromJSON('{"branch":"Staging","tag":"Production"}')[github.ref_type] }}
    env:
      TEST_ENV: ${{ fromJSON('{"branch":"$ASDF","tag":"this is a tag"}')[github.ref_type] }}
      STAGE: ${{ secrets.STAGING }}
      PROD: ${{ secrets.PROD }}
    steps:
    - name: Checkout repository code
      uses: actions/checkout@v3
    - name: Use Node.js 16
      uses: actions/setup-node@v3
      with:
        always-auth: true
        node-version: 16.x
        registry-url: https://npm.pkg.github.com
    - name: what env am i in
      run: |
        echo ${{ secrets.STAGING }}
        echo ${{ secrets.PROD }}
    - name: Get previous tagged release
      if: github.ref_type == 'tag'
      run: |
        git fetch --tags --force origin
        echo "PREVIOUS_TAG=$(git tag --list --sort=-v:refname | head -2 | tail -1)" >> $GITHUB_ENV
    # Action reference: https://github.com/dorny/paths-filter
    - uses: dorny/paths-filter@v2
      if: github.ref_type == 'tag'
      id: filter
      with:
        filters: |
          test1:
            - 'packages/test-package-1/**'
          test2:
            - 'packages/test-package-2/**'
        base: ${{ env.PREVIOUS_TAG }}
    - name: Print filter results
      if: github.ref_type == 'tag'
      run: |
        echo "test-package-1 changed? ${{ steps.filter.outputs.test1 }}"
        echo "test-package-2 changed? ${{ steps.filter.outputs.test2 }}"
    - name: What is this? This is ${{ env.TEST_ENV }}
      run: echo $TEST_ENV
    - run: echo ${{ github.ref }}
    - run: echo ${{ github.base_ref }}
    - run: echo ${{ github.head_ref }}
    - run: echo ${GITHUB_REF}
    - run: echo ${GITHUB_REF##*/}
    - run: echo ${GITHUB_BASE_REF}
    - run: echo ${GITHUB_BASE_REF##*/}
    - run: echo ${GITHUB_HEAD_REF}
    - run: echo ${GITHUB_HEAD_REF##*/}
    - run: git branch --show-current
    - run: env
    - name: Install Deps
      run: npm ci --ignore-scripts
      env:
        NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Run Program
      run: node .
    - name: Run script
      run: npm run gha
    - run: echo $NEW_VAR
      env:
        NEW_VAR: ${{ env.MY_ENV }}
  tag:
    if: ${{ github.ref_type == 'tag' }}
    runs-on: ubuntu-latest
    steps:
    - name: what env am i in
      run: |
        echo ${{ secrets.STAGING }}
        echo ${{ secrets.PROD }}
  dep_branch:
    runs-on: ubuntu-latest
    needs: [ branch ]
    steps:
    - name: what env am i in
      run: echo "Hello dep_branch"
    - name: Set env NEED
      run: |
        if [[ ${{ github.ref_type }} == 'branch']]; then
            echo TYPE=${{ github.ref_type }} >> $GITHUB_ENV
        else
            echo TYPE=${{ github.event_name }} >> $GITHUB_ENV
        fi
    - run: echo $TYPE
  dep_tag:
    runs-on: ubuntu-latest
    needs: [ tag ]
    steps:
    - name: what env am i in
      run: echo "Hello dep_tag"
