name: Test Github Packages - Push

on:
  push:
    branches: [ main ]
    tags: [ v1* ]
    
jobs:
  test_github_actions_push:
    runs-on: ubuntu-latest
    env:
      TEST_ENV: ${{ fromJSON('{"branch":"this is a branch","tag":"this is a tag"}')[github.ref_type] }}
    strategy:
      matrix:
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
        node-version: [16.x]
    steps:
    - name: Checkout repository code
      uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        always-auth: true
        node-version: ${{ matrix.node-version }}
        registry-url: https://npm.pkg.github.com
    - name: Get previous tagged release
      if: github.ref_type == 'tag'
      run: |
        git fetch --tags origin
        echo "PREVIOUS_TAG=$(git tag --list --sort=-v:refname "millerknoll-site@*" | head -2 | tail -1)" >> $GITHUB_ENV
    # Action reference: https://github.com/dorny/paths-filter
    - uses: dorny/paths-filter@v2
      if: github.ref_type == 'tag'
      id: filter
      with:
        filters: |
          test1:
            - 'packages/test-package-1/**'
          test2:
            - 'packages/test-package-2/**'
        base: ${{ env.PREVIOUS_TAG }}
    - name: Print filter results
      if: github.ref_type == 'tag'
      run: |
        echo "test-package-1 changed? ${{ steps.filter.outputs.test1 }}"
        echo "test-package-2 changed? ${{ steps.filter.outputs.test2 }}"
    - name: What is this? This is ${{ env.TEST_ENV }}
      run: echo $TEST_ENV
    - run: echo ${{ github.ref }}
    - run: echo ${{ github.base_ref }}
    - run: echo ${{ github.head_ref }}
    - run: echo ${GITHUB_REF}
    - run: echo ${GITHUB_REF##*/}
    - run: echo ${GITHUB_BASE_REF}
    - run: echo ${GITHUB_BASE_REF##*/}
    - run: echo ${GITHUB_HEAD_REF}
    - run: echo ${GITHUB_HEAD_REF##*/}
    - run: git branch --show-current
    - run: env
    - name: Install Deps
      run: npm ci --ignore-scripts
      env:
        NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Run Program
      run: node .
    - name: Run script
      run: npm run gha
    - run: echo $NEW_VAR
      env:
        NEW_VAR: ${{ env.MY_ENV }}
